baseURL = 'https://wiki.moobug.net/'
languageCode = 'en-gb'
title = 'Moobug Wiki'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"
enableEmoji = true

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "SEARCH"]

[params]
  disableExplicitIndexURLs = true
