site_name: Moobug Wiki
site_url: https://wiki.moobug.net
repo_url: https://github.com/thelovebug/wiki.moobug.net
theme:
  name: 'material'
  icon:
    logo: octicons/bug-16
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: 'amber'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Embrace the dark side
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs

extra_css: [ "extra.css" ]
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false
  - tables
  - toc:
      permalink: true


extra:
  social:
    - icon: 'fontawesome/brands/telegram'
      link: 'https://t.me/thelovebug'
    - icon: 'fontawesome/brands/mastodon'
      link: 'https://mastodon.me.uk/@thelovebug'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/thelovebug'
