site_name: Moobug Wiki
site_url: https://wiki.moobug.net
repo_url: https://github.com/thelovebug/wiki.moobug.net
theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: 'amber'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Embrace the dark side
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs

markdown_extensions:
  - admonition
  - attr_list
  #- def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false
  - tables
  - toc:
      permalink: true


extra:
  social:
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/npwFgnj2vU'
    - icon: 'fontawesome/brands/telegram'
      link: 'https://t.me/hamsoverip'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/hamsoverip'
    - icon: 'fontawesome/brands/mastodon'
      link: 'https://mastodon.radio/@hamsoverip'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/hamsoverip'
    - icon: 'fontawesome/brands/snapchat'
      link: 'https://www.snapchat.com/add/hamsoverip?share_id=Zb3vtgDNUCU&locale=en-US'  
    - icon: 'fontawesome/brands/reddit'
      link: 'https://www.reddit.com/r/hamsoverip/'      
